
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'FinanceApp'

target 'FinanceApp' do
  pod 'SwiftGen', '6.5.1'
  target 'FinanceAppTests' do
  end
end