#==================================================================================================
# Xcodegen documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme
#==================================================================================================

name: FinanceApp

settings: 
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  bundleIdPrefix: com.devpass.
  xcodeVersion: "13.2"
  deploymentTarget:
    iOS: "13.0"

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    branch: master

targets: 

  FinanceApp:
    platform: iOS
    type: application
    
    sources:
      - path: FinanceApp
    
    dependencies:
      - target: Service
    
    # Adicionando um script de pre build para executar o SwiftGen
    preBuildScripts:
      - script: "${PODS_ROOT}/SwiftGen/bin/swiftgen"
        name: SwiftGen
    
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: FinanceApp
      INFOPLIST_FILE: FinanceApp/Resources/Info.plist
      CODE_SIGN_STYLE: "Manual"
      DEVELOPMENT_TEAM: ""
      PROVISIONING_PROFILE: "Wildcard"
  
  FinanceAppTests:
    platform: iOS
    type: bundle.unit-test

    sources:
      - path: FinanceAppTests
  
    dependencies:
      - target: FinanceApp

  Service:
    templates:
      - Framework
    dependencies:
      - package: Alamofire
    
schemes:
  FinanceApp:
    build:
      targets:
        FinanceApp: [run, test]
      parallelizeBuild: true
      buildImplicitDependencies: true
    run:
      config: Debug
    test: 
      config: Debug
      gatherCoverageData: true
      coverageTargets: 
        - FinanceApp
      targets:
        - FinanceAppTests

targetTemplates:
  Framework:
    platform: iOS
    type: framework
    sources: 
      - path: ${target_name}
    info:
      path: ${target_name}/Info.plist